apiVersion: v1
data:
  init.sql: "CREATE TABLE IF NOT EXISTS targeting_rules (\r\n    id SERIAL PRIMARY
    KEY,\r\n\r\n    -- 'flag_name' é a chave de negócio única. \r\n    -- Cada flag
    pode ter no máximo UMA regra de segmentação.\r\n    flag_name VARCHAR(100) UNIQUE
    NOT NULL,\r\n    \r\n    -- Se a regra de segmentação em si está ativa ou não\r\n
    \   is_enabled BOOLEAN NOT NULL DEFAULT true,\r\n    \r\n    -- Armazena a lógica
    da regra como um JSON.\r\n    -- Ex: {\"type\": \"PERCENTAGE\", \"value\": 50}\r\n
    \   -- Ex: {\"type\": \"USER_LIST\", \"values\": [\"u1\", \"u2\"]}\r\n    rules
    JSONB NOT NULL,\r\n    \r\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,\r\n
    \   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP\r\n);\r\n\r\n--
    Trigger para atualizar 'updated_at' automaticamente (igual ao do flag-service)\r\nCREATE
    OR REPLACE FUNCTION trigger_set_timestamp()\r\nRETURNS TRIGGER AS $$\r\nBEGIN\r\n
    \ NEW.updated_at = NOW();\r\n  RETURN NEW;\r\nEND;\r\n$$ LANGUAGE plpgsql;\r\n\r\nDROP
    TRIGGER IF EXISTS set_timestamp ON targeting_rules;\r\n\r\nCREATE TRIGGER set_timestamp\r\nBEFORE
    UPDATE ON targeting_rules\r\nFOR EACH ROW\r\nEXECUTE PROCEDURE trigger_set_timestamp();"
kind: ConfigMap
metadata:
  name: targeting-db-init-sql
  namespace: togglemaster
