apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
stringData:
  AUTH_DATABASE_URL: "postgres://togglemaster:SENHA_AUTH_URL_ENCODED@togglemaster-auth-db.example.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  FLAG_DATABASE_URL: "postgres://togglemaster:SENHA_FLAG_URL_ENCODED@togglemaster-flag-db.example.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require"
  TARGETING_DATABASE_URL: "postgres://togglemaster:SENHA_TARGETING_URL_ENCODED@togglemaster-targeting-db.example.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require"
  MASTER_KEY: "troque-esta-master-key"
  SERVICE_API_KEY: "tm_key_exemplo"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "COLE_A_ACCESS_KEY_TEMPORARIA_DO_AWS_ACADEMY"
  AWS_SECRET_ACCESS_KEY: "COLE_A_SECRET_KEY_TEMPORARIA_DO_AWS_ACADEMY"
  AWS_SESSION_TOKEN: "COLE_O_SESSION_TOKEN_TEMPORARIO_DO_AWS_ACADEMY"